### ISSUE TITLE
Function not implemented (/home/conan/w/BuildSingleReference/.conan/data/zeromq/4.3.4/_/_/build/16af9af26a452448a2cd2c63dacfde86f7fbfb27/source_subfolder/src/ip.cpp:563)

### ISSUE THREAD

**Issue by riturajsingh487** [gramineproject/gramine#835]
### I am trying to create a secure client-server architecture using Zero-mq and Protocol buffers. While running the server linux binary with gramine I am getting below error.

**Function not implemented (/home/conan/w/BuildSingleReference/.conan/data/zeromq/4.3.4/_/_/build/16af9af26a452448a2cd2c63dacfde86f7fbfb27/source_subfolder/src/ip.cpp:563)**

Please find below the error logs while running the binary with gramine

---------------------------------------------------------------------------------------------------------------------------------------

Gramine is starting. Parsing TOML manifest file, this may take some time...
debug: Gramine parsed TOML manifest file successfully
debug: Token file: ServerZP.token
debug: Read dummy DCAP token
debug: Enclave created:
debug:     base:           0x0000000000000000
debug:     size:           0x0000000010000000
debug:     misc_select:    0x00000000
debug:     attr.flags:     0x0000000000000007
debug:     attr.xfrm:      0x0000000000000007
debug:     ssa_frame_size: 4
debug:     isv_prod_id:    0x00000000
debug:     isv_svn:        0x00000000
debug: Adding pages to SGX enclave, this may take some time...
debug: Adding pages to enclave: 0xfed1000-0x10000000 [REG:R--] (manifest) measured
debug: Adding pages to enclave: 0xfeb1000-0xfed1000 [REG:RW-] (ssa) measured
debug: Adding pages to enclave: 0xfead000-0xfeb1000 [TCS:---] (tcs) measured
debug: Adding pages to enclave: 0xfea9000-0xfead000 [REG:RW-] (tls) measured
debug: Adding pages to enclave: 0xfe69000-0xfea9000 [REG:RW-] (stack) measured
debug: Adding pages to enclave: 0xfe29000-0xfe69000 [REG:RW-] (stack) measured
debug: Adding pages to enclave: 0xfde9000-0xfe29000 [REG:RW-] (stack) measured
debug: Adding pages to enclave: 0xfda9000-0xfde9000 [REG:RW-] (stack) measured
debug: Adding pages to enclave: 0xfd99000-0xfda9000 [REG:RW-] (sig_stack) measured
debug: Adding pages to enclave: 0xfd89000-0xfd99000 [REG:RW-] (sig_stack) measured
debug: Adding pages to enclave: 0xfd79000-0xfd89000 [REG:RW-] (sig_stack) measured
debug: Adding pages to enclave: 0xfd69000-0xfd79000 [REG:RW-] (sig_stack) measured
debug: Adding pages to enclave: 0xf94e000-0xf991000 [REG:R-X] (code) measured
debug: Adding pages to enclave: 0xf991000-0xf995000 [REG:RW-] (data) measured
debug: Adding pages to enclave: 0xf995000-0xfd69000 [REG:RW-] (bss) measured
debug: Adding pages to enclave: 0x10000-0xf94e000 [REG:RWX] (free)
debug: Added all pages to SGX enclave
debug: Enclave initializing:
debug:     enclave id:   0x000000000ffff000
debug:     mr_enclave:   46fe578d556080821dca93950bca1afab8012c293b73b6bbcc68aef2df260d8e
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - loader.log_level = warning|debug|trace|all (verbose log level, may leak information)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

warning: DkVirtualMemoryProtect is unimplemented in Linux-SGX PAL
[::] debug: Gramine was built from commit: 1.2
[::] debug: Host: Linux-SGX
[::] debug: LibOS xsave_enabled 1, xsave_size 0x340(832), xsave_features 0x7
[::] debug: Initial VMA region 0xf0a1000-0xf140000 (LibOS) bookkeeped
[::] debug: Initial VMA region 0xfed1000-0x10000000 (manifest) bookkeeped
[::] debug: ASLR top address adjusted to 0x3e74000
[::] debug: host is Linux-SGX, adding SGX-specific /dev/attestation files: report, quote, etc.
[::] debug: Shim loaded at 0xf0a1000, ready to initialize
[::] debug: mounting "file:." (chroot) under /
[::] debug: mounting "proc" (pseudo) under /proc
[::] debug: mounting "dev" (pseudo) under /dev
[::] debug: mounting "dev:tty" (chroot) under /dev/tty
[::] debug: mounting "sys" (pseudo) under /sys
[::] debug: Creating pipe: pipe.srv:069cfe72891cd9cdcc94110a3bd75e20dcee9b6ceb9a65db37305ffd7ec718cf
[P1:T1:] debug: mounting "file:/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc" (chroot) under /lib
[P1:T1:] debug: mounting "file:/usr/lib/x86_64-linux-gnu/" (chroot) under /usr/lib/x86_64-linux-gnu/
[P1:T1:] debug: mounting "file:/usr/lib32/" (chroot) under /usr/lib32/
[P1:T1:] debug: mounting "file:/tmp/" (chroot) under /tmp
[P1:T1:ServerZP] debug: Creating pipe: pipe.srv:c560bc36eee2dfd18641ab69cb37f28f870c37e6d510a94bc512da6d0bb6806c
[P1:T1:ServerZP] debug: Allocating stack at 0 (size = 262144)
[P1:T1:ServerZP] debug: loading "file:./ServerZP"
[P1:T1:ServerZP] debug: find_interp: searching for interpreter: /lib/ld-linux-x86-64.so.2
[P1:T1:ServerZP] debug: loading "file:/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc/ld-linux-x86-64.so.2"
[P1:T1:ServerZP] debug: Creating pipe: pipe.srv:1
[P1:T1:ServerZP] debug: Creating pipe: pipe.srv:58c5c9467f0d4acf4e36ed71f4eefa6eb5b2c44679bcb77b9fb8a0e102c81a10
[P1:T1:ServerZP] debug: Shim process initialized
[P1:T1:ServerZP] trace: ---- shim_brk(0) = 0x48ee000
[P1:shim] debug: IPC worker started
[P1:T1:ServerZP] trace: ---- shim_uname(0x3e73970) = 0x0
[P1:T1:ServerZP] trace: ---- shim_mmap(0, 0x2000, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0x0) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x37fa000
[P1:T1:ServerZP] trace: ---- shim_access("/etc/ld.so.preload", F_OK|X_OK) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/lib/glibc-hwcaps/x86-64-v3/libdl.so.2", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/lib/glibc-hwcaps/x86-64-v3", 0x3e72fb0, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/lib/glibc-hwcaps/x86-64-v2/libdl.so.2", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/lib/glibc-hwcaps/x86-64-v2", 0x3e72fb0, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/lib/tls/haswell/x86_64/libdl.so.2", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/lib/tls/haswell/x86_64", 0x3e72fb0, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/lib/tls/haswell/libdl.so.2", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/lib/tls/haswell", 0x3e72fb0, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/lib/tls/x86_64/libdl.so.2", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/lib/tls/x86_64", 0x3e72fb0, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/lib/tls/libdl.so.2", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/lib/tls", 0x3e72fb0, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/lib/haswell/x86_64/libdl.so.2", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/lib/haswell/x86_64", 0x3e72fb0, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/lib/haswell/libdl.so.2", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/lib/haswell", 0x3e72fb0, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/lib/x86_64/libdl.so.2", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/lib/x86_64", 0x3e72fb0, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/lib/libdl.so.2", O_RDONLY|0x80000, 0000) = 0x3
[P1:T1:ServerZP] trace: ---- shim_read(3, 0x3e73108, 0x340) ...
[P1:T1:ServerZP] trace: ---- return from shim_read(...) = 0x340
[P1:T1:ServerZP] trace: ---- shim_newfstatat(3, "", 0x3e72fb0, 4096) = 0x0
[P1:T1:ServerZP] trace: ---- shim_mmap(0, 0x4028, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0x0) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x37f5000
[P1:T1:ServerZP] trace: ---- shim_mmap(0x37f6000, 0x1000, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1000) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x37f6000
[P1:T1:ServerZP] trace: ---- shim_mmap(0x37f7000, 0x1000, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x37f7000
[P1:T1:ServerZP] trace: ---- shim_mmap(0x37f8000, 0x2000, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x37f8000
[P1:T1:ServerZP] trace: ---- shim_close(3) = 0x0
[P1:T1:ServerZP] debug: glibc register library /lib/libdl.so.2 loaded at 0x037f5000
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/lib/libpthread.so.0", O_RDONLY|0x80000, 0000) = 0x3
[P1:T1:ServerZP] trace: ---- shim_read(3, 0x3e730e8, 0x340) ...
[P1:T1:ServerZP] trace: ---- return from shim_read(...) = 0x340
[P1:T1:ServerZP] trace: ---- shim_newfstatat(3, "", 0x3e72f90, 4096) = 0x0
[P1:T1:ServerZP] trace: ---- shim_mmap(0, 0x2000, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0x0) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x37f3000
[P1:T1:ServerZP] trace: ---- shim_mmap(0, 0x4028, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0x0) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x37ee000
[P1:T1:ServerZP] trace: ---- shim_mmap(0x37ef000, 0x1000, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1000) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x37ef000
[P1:T1:ServerZP] trace: ---- shim_mmap(0x37f0000, 0x1000, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x37f0000
[P1:T1:ServerZP] trace: ---- shim_mmap(0x37f1000, 0x2000, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x37f1000
[P1:T1:ServerZP] trace: ---- shim_close(3) = 0x0
[P1:T1:ServerZP] debug: glibc register library /lib/libpthread.so.0 loaded at 0x037ee000
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/lib/libstdc++.so.6", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib32/glibc-hwcaps/x86-64-v3/libstdc++.so.6", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/usr/lib32/glibc-hwcaps/x86-64-v3", 0x3e72f70, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib32/glibc-hwcaps/x86-64-v2/libstdc++.so.6", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/usr/lib32/glibc-hwcaps/x86-64-v2", 0x3e72f70, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib32/tls/haswell/x86_64/libstdc++.so.6", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/usr/lib32/tls/haswell/x86_64", 0x3e72f70, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib32/tls/haswell/libstdc++.so.6", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/usr/lib32/tls/haswell", 0x3e72f70, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib32/tls/x86_64/libstdc++.so.6", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/usr/lib32/tls/x86_64", 0x3e72f70, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib32/tls/libstdc++.so.6", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/usr/lib32/tls", 0x3e72f70, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib32/haswell/x86_64/libstdc++.so.6", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/usr/lib32/haswell/x86_64", 0x3e72f70, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib32/haswell/libstdc++.so.6", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/usr/lib32/haswell", 0x3e72f70, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib32/x86_64/libstdc++.so.6", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/usr/lib32/x86_64", 0x3e72f70, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib32/libstdc++.so.6", O_RDONLY|0x80000, 0000) = 0x3
[P1:T1:ServerZP] trace: ---- shim_read(3, 0x3e730c8, 0x340) ...
[P1:T1:ServerZP] trace: ---- return from shim_read(...) = 0x340
[P1:T1:ServerZP] trace: ---- shim_close(3) = 0x0
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/usr/lib32", 0x3e72f70, 0) = 0x0
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3/libstdc++.so.6", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3", 0x3e72f70, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v2/libstdc++.so.6", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v2", 0x3e72f70, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/tls/haswell/x86_64/libstdc++.so.6", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/tls/haswell/x86_64", 0x3e72f70, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/tls/haswell/libstdc++.so.6", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/tls/haswell", 0x3e72f70, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/tls/x86_64/libstdc++.so.6", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/tls/x86_64", 0x3e72f70, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/tls/libstdc++.so.6", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/tls", 0x3e72f70, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/haswell/x86_64/libstdc++.so.6", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/haswell/x86_64", 0x3e72f70, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/haswell/libstdc++.so.6", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/haswell", 0x3e72f70, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/x86_64/libstdc++.so.6", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/x86_64", 0x3e72f70, 0) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/libstdc++.so.6", O_RDONLY|0x80000, 0000) = 0x3
[P1:T1:ServerZP] trace: ---- shim_read(3, 0x3e730c8, 0x340) ...
[P1:T1:ServerZP] trace: ---- return from shim_read(...) = 0x340
[P1:T1:ServerZP] trace: ---- shim_newfstatat(3, "", 0x3e72f70, 4096) = 0x0
[P1:T1:ServerZP] trace: ---- shim_mmap(0, 0x1e1800, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0x0) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x360c000
[P1:T1:ServerZP] trace: ---- shim_mprotect(0x36a2000, 0x13b000, PROT_NONE) ...
[P1:T1:ServerZP] trace: ---- return from shim_mprotect(...) = 0x0
[P1:T1:ServerZP] trace: ---- shim_mmap(0x36a2000, 0xf1000, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x96000) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x36a2000
[P1:T1:ServerZP] trace: ---- shim_mmap(0x3793000, 0x49000, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x187000) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x3793000
[P1:T1:ServerZP] trace: ---- shim_mmap(0x37dd000, 0xe000, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1d0000) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x37dd000
[P1:T1:ServerZP] trace: ---- shim_mmap(0x37eb000, 0x2800, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED, -1, 0x0) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x37eb000
[P1:T1:ServerZP] trace: ---- shim_close(3) = 0x0
[P1:T1:ServerZP] debug: glibc register library /usr/lib/x86_64-linux-gnu/libstdc++.so.6 loaded at 0x0360c000
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/lib/libgcc_s.so.1", O_RDONLY|0x80000, 0000) = -2
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib32/libgcc_s.so.1", O_RDONLY|0x80000, 0000) = 0x3
[P1:T1:ServerZP] trace: ---- shim_read(3, 0x3e730a8, 0x340) ...
[P1:T1:ServerZP] trace: ---- return from shim_read(...) = 0x340
[P1:T1:ServerZP] trace: ---- shim_close(3) = 0x0
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/libgcc_s.so.1", O_RDONLY|0x80000, 0000) = 0x3
[P1:T1:ServerZP] trace: ---- shim_read(3, 0x3e730a8, 0x340) ...
[P1:T1:ServerZP] trace: ---- return from shim_read(...) = 0x340
[P1:T1:ServerZP] trace: ---- shim_newfstatat(3, "", 0x3e72f50, 4096) = 0x0
[P1:T1:ServerZP] trace: ---- shim_mmap(0, 0x1a448, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0x0) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x35f1000
[P1:T1:ServerZP] trace: ---- shim_mmap(0x35f4000, 0x12000, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x35f4000
[P1:T1:ServerZP] trace: ---- shim_mmap(0x3606000, 0x4000, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x15000) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x3606000
[P1:T1:ServerZP] trace: ---- shim_mmap(0x360a000, 0x2000, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x18000) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x360a000
[P1:T1:ServerZP] trace: ---- shim_close(3) = 0x0
[P1:T1:ServerZP] debug: glibc register library /usr/lib/x86_64-linux-gnu/libgcc_s.so.1 loaded at 0x035f1000
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/lib/libc.so.6", O_RDONLY|0x80000, 0000) = 0x3
[P1:T1:ServerZP] trace: ---- shim_read(3, 0x3e73088, 0x340) ...
[P1:T1:ServerZP] trace: ---- return from shim_read(...) = 0x340
[P1:T1:ServerZP] trace: ---- shim_pread64(3, 0x3e72aa0, 0x310, 0x40) ...
[P1:T1:ServerZP] trace: ---- return from shim_pread64(...) = 0x310
[P1:T1:ServerZP] trace: ---- shim_pread64(3, 0x3e72a70, 0x20, 0x350) ...
[P1:T1:ServerZP] trace: ---- return from shim_pread64(...) = 0x20
[P1:T1:ServerZP] trace: ---- shim_pread64(3, 0x3e72a20, 0x44, 0x370) ...
[P1:T1:ServerZP] trace: ---- return from shim_pread64(...) = 0x44
[P1:T1:ServerZP] trace: ---- shim_newfstatat(3, "", 0x3e72f30, 4096) = 0x0
[P1:T1:ServerZP] trace: ---- shim_pread64(3, 0x3e72b80, 0x310, 0x40) ...
[P1:T1:ServerZP] trace: ---- return from shim_pread64(...) = 0x310
[P1:T1:ServerZP] trace: ---- shim_mmap(0, 0x1f3a50, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0x0) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x33fd000
[P1:T1:ServerZP] trace: ---- shim_mmap(0x3429000, 0x165000, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2c000) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x3429000
[P1:T1:ServerZP] trace: ---- shim_mmap(0x358e000, 0x55000, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x191000) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x358e000
[P1:T1:ServerZP] trace: ---- shim_mmap(0x35e3000, 0x6000, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1e5000) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x35e3000
[P1:T1:ServerZP] trace: ---- shim_mmap(0x35e9000, 0x7a50, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED, -1, 0x0) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x35e9000
[P1:T1:ServerZP] trace: ---- shim_close(3) = 0x0
[P1:T1:ServerZP] debug: glibc register library /lib/libc.so.6 loaded at 0x033fd000
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/lib/libm.so.6", O_RDONLY|0x80000, 0000) = 0x3
[P1:T1:ServerZP] trace: ---- shim_read(3, 0x3e73048, 0x340) ...
[P1:T1:ServerZP] trace: ---- return from shim_read(...) = 0x340
[P1:T1:ServerZP] trace: ---- shim_newfstatat(3, "", 0x3e72ef0, 4096) = 0x0
[P1:T1:ServerZP] trace: ---- shim_mmap(0, 0xda0f8, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0x0) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x3322000
[P1:T1:ServerZP] trace: ---- shim_mprotect(0x3331000, 0xca000, PROT_NONE) ...
[P1:T1:ServerZP] trace: ---- return from shim_mprotect(...) = 0x0
[P1:T1:ServerZP] trace: ---- shim_mmap(0x3331000, 0x6f000, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xf000) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x3331000
[P1:T1:ServerZP] trace: ---- shim_mmap(0x33a0000, 0x5a000, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x7e000) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x33a0000
[P1:T1:ServerZP] trace: ---- shim_mmap(0x33fb000, 0x2000, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xd8000) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x33fb000
[P1:T1:ServerZP] trace: ---- shim_close(3) = 0x0
[P1:T1:ServerZP] debug: glibc register library /lib/libm.so.6 loaded at 0x03322000
[P1:T1:ServerZP] trace: ---- shim_mmap(0, 0x2000, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0x0) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x3320000
[P1:T1:ServerZP] trace: ---- shim_mmap(0, 0x3000, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0x0) ...
[P1:T1:ServerZP] trace: ---- return from shim_mmap(...) = 0x331d000
[P1:T1:ServerZP] trace: ---- shim_arch_prctl(4098, 0x331d740) = 0x0
[P1:T1:ServerZP] trace: ---- shim_set_tid_address(0x331da10) = 0x1
[P1:T1:ServerZP] trace: ---- shim_set_robust_list(0x331da20, 0x18) = 0x0
[P1:T1:ServerZP] trace: ---- shim_mprotect(0x35e3000, 0x3000, PROT_READ) ...
[P1:T1:ServerZP] trace: ---- return from shim_mprotect(...) = 0x0
[P1:T1:ServerZP] trace: ---- shim_mprotect(0x33fb000, 0x1000, PROT_READ) ...
[P1:T1:ServerZP] trace: ---- return from shim_mprotect(...) = 0x0
[P1:T1:ServerZP] trace: ---- shim_mprotect(0x360a000, 0x1000, PROT_READ) ...
[P1:T1:ServerZP] trace: ---- return from shim_mprotect(...) = 0x0
[P1:T1:ServerZP] trace: ---- shim_mprotect(0x37dd000, 0xb000, PROT_READ) ...
[P1:T1:ServerZP] trace: ---- return from shim_mprotect(...) = 0x0
[P1:T1:ServerZP] trace: ---- shim_mprotect(0x37f1000, 0x1000, PROT_READ) ...
[P1:T1:ServerZP] trace: ---- return from shim_mprotect(...) = 0x0
[P1:T1:ServerZP] trace: ---- shim_mprotect(0x37f8000, 0x1000, PROT_READ) ...
[P1:T1:ServerZP] trace: ---- return from shim_mprotect(...) = 0x0
[P1:T1:ServerZP] trace: ---- shim_mprotect(0x3df1000, 0x38000, PROT_READ) ...
[P1:T1:ServerZP] trace: ---- return from shim_mprotect(...) = 0x0
[P1:T1:ServerZP] trace: ---- shim_mprotect(0x382c000, 0x2000, PROT_READ) ...
[P1:T1:ServerZP] trace: ---- return from shim_mprotect(...) = 0x0
[P1:T1:ServerZP] trace: ---- shim_prlimit64(0, 3, 0, 0x3e73b00) = 0x0
[P1:T1:ServerZP] trace: ---- shim_getrandom(0x35ee178, 0x8, GRND_NONBLOCK) = 0x8
[P1:T1:ServerZP] trace: ---- shim_brk(0) = 0x48ee000
[P1:T1:ServerZP] trace: ---- shim_brk(0x490f000) = 0x490f000
[P1:T1:ServerZP] trace: ---- shim_futex(0x37eb6bc, FUTEX_PRIVATE|FUTEX_WAKE, 2147483647, 0, 0xca, 1) ...
[P1:T1:ServerZP] trace: ---- return from shim_futex(...) = 0x0
[P1:T1:ServerZP] trace: ---- shim_futex(0x37eb6c8, FUTEX_PRIVATE|FUTEX_WAKE, 2147483647, 0, 0xca, 1) ...
[P1:T1:ServerZP] trace: ---- return from shim_futex(...) = 0x0
[P1:T1:ServerZP] trace: ---- shim_getcwd(0x3e737b0, 0x400) = 0x2
[P1:T1:ServerZP] trace: ---- shim_newfstatat(1, "", 0x3e73a20, 4096) = 0x0
[P1:T1:ServerZP] trace: ---- shim_ioctl(1, TCGETS, 0x3e73990) ...
[P1:T1:ServerZP] trace: ---- return from shim_ioctl(...) = -38
[P1:T1:ServerZP] trace: ---- shim_stat("/tmp", 0x3e73ae0) = 0x0
[P1:T1:ServerZP] trace: ---- shim_openat(AT_FDCWD, "/dev/urandom", O_RDONLY, 0000) = 0x3
[P1:T1:ServerZP] trace: ---- shim_read(3, 0x3e73240, 0x10) ...
[P1:T1:ServerZP] trace: ---- return from shim_read(...) = 0x10
[P1:T1:ServerZP] trace: ---- shim_close(3) = 0x0
[P1:T1:ServerZP] trace: ---- shim_stat("/tmp/bc88_fe6f_f702_4217", 0x3e731e0) = -2
[P1:T1:ServerZP] trace: ---- shim_stat("/tmp/bc88_fe6f_f702_4217", 0x3e73130) = -2
[P1:T1:ServerZP] trace: ---- shim_stat("/tmp", 0x3e73130) = 0x0
[P1:T1:ServerZP] trace: ---- shim_mkdir("/tmp/bc88_fe6f_f702_4217", 511) = 0x0
[P1:T1:ServerZP] trace: ---- shim_stat("/home/specs/Rituraj", 0x3e732a0) = -2
[P1:T1:ServerZP] warning: The app tried to use eventfd, but it's turned off (sys.insecure__allow_eventfd = false)
[P1:T1:ServerZP] trace: ---- shim_eventfd2(0, 524288) = -38
[P1:T1:ServerZP] trace: ---- shim_write(2, 0x3e718c0, 0xaa) ...
**Function not implemented (/home/conan/w/BuildSingleReference/.conan/data/zeromq/4.3.4/_/_/build/16af9af26a452448a2cd2c63dacfde86f7fbfb27/source_subfolder/src/ip.cpp:563)**
[P1:T1:ServerZP] trace: ---- return from shim_write(...) = 0xaa
[P1:T1:ServerZP] trace: ---- shim_rt_sigprocmask(UNBLOCK, [SIGABRT,], NULL, 0x8) = 0x0
[P1:T1:ServerZP] trace: ---- shim_gettid() = 0x1
[P1:T1:ServerZP] trace: ---- shim_getpid() = 0x1
[P1:T1:ServerZP] trace: ---- shim_tgkill(1, 1, [SIGABRT]) = 0x0
[P1:T1:ServerZP] debug: killed by signal 6
[P1:T1:ServerZP] debug: clearing POSIX locks for pid 1
[P1:T1:ServerZP] debug: sync client shutdown: closing handles
[P1:T1:ServerZP] debug: sync client shutdown: waiting for confirmation
[P1:T1:ServerZP] debug: sync client shutdown: finished
[P1:shim] debug: IPC worker: exiting worker thread
[P1:T1:ServerZP] debug: process 1 exited with status 134
debug: DkProcessExit: Returning exit code 134

'''

Also find below the readelf output of binary

----------------------------------------------------------------------------------------------------------------

>   1186: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS **ip.cpp**
>   1187: 00000000005fa920    32 OBJECT  LOCAL  DEFAULT   26 _ZL12tmp_env_vars
>   1188: 00000000000737a8    49 FUNC    LOCAL  DEFAULT   14 _ZN3zmq27create_ipc_wildc

-----------------------------------------------------------------------------------------------------------------------------

## Steps to reproduce

Running the binary with gramine : 
gramine-sgx ServerZP

---------------------------------------------------------------------------------------------------------------
Below is the manifest file for reference:

[loader]
entrypoint = "file:/usr/lib/x86_64-linux-gnu/gramine/libsysdb.so"
log_level = "trace"
argv0_override = "ServerZP"

[libos]
entrypoint = "ServerZP"

[fs]
[[fs.mounts]]
path = "/lib"
uri = "file:/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc"

[[fs.mounts]]
path = "/usr/lib/x86_64-linux-gnu/"
uri = "file:/usr/lib/x86_64-linux-gnu/"

[[fs.mounts]]
path = "/usr/lib32/"
uri = "file:/usr/lib32/"

[[fs.mounts]]
path = "/tmp"
uri = "file:/tmp/"

[sgx]
debug = true
nonpie_binary = true
enclave_size = "256M"
thread_num = 4
isvprodid = 0
isvsvn = 0
remote_attestation = false
require_avx = false
require_avx512 = false
require_mpx = false
require_pkru = false
require_amx = false
support_exinfo = false
enable_stats = false
[[sgx.trusted_files]]
uri = "file:/usr/lib/x86_64-linux-gnu/gramine/libsysdb.so"

[[sgx.trusted_files]]
uri = "file:ServerZP"

[[sgx.trusted_files]]
uri = "file:/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc/"

**Comment by boryspoplawski** [comment]
Please use proper markdown syntax, this is hardly readable.

**Comment by kailun-qin** [comment]
Looks like your zeromq workload is trying to use eventfd, pls kindly have a try on adding `sys.insecure__allow_eventfd = true` into the manifest or disabling eventfd in the zeromq configure script w/ `--disable-eventfd` (default enabled).

**Comment by riturajsingh487** [comment]
Thanks for the reply.
That error is not coming after adding **sys.insecure__allow_eventfd = true**  in the manifest file as you suggested . 

I am running server linux binary with gramine.
Now, it is stuck at some point while calling **shim_epoll_wait()**, **call has not reached the main()** yet in which I am creating a socket using zeromq. (Server)

Still I tried connecting the server with my client application and I could see some system calls at the server side  but after few seconds server running on gramine gets terminated.

I could also see some warnings:  **[P1:T3:ServerZP] warning: Unsupported system call prctl**
and this log : **terminate called after throwing an instance of 'std::out_of_range'**

Any help on this is greatly appreciated.

I have attached logs for you reference, (Logs after line 1109 starts  after trying to connect from client application)

[gramine_server_epoll_zeromq_logs.txt](https://github.com/gramineproject/gramine/files/9329450/gramine_server_epoll_zeromq_logs.txt)

**Comment by dimakuv** [comment]
> and this log : terminate called after throwing an instance of 'std::out_of_range'

The size of your SGX enclave is only 256MB. I suggest you to increment it to smth like 1GB, using the `sgx.enclave_size = "1G"` manifest option.

**Comment by riturajsingh487** [comment]
I tried increasing the size of the SGX enclave to 1GB and 2GB. But still no luck. Same issue is coming.
Here is my manifest.template file

[ServerZP.manifest.template.txt](https://github.com/gramineproject/gramine/files/9352500/ServerZP.manifest.template.txt)

Your help on this is greatly appreciated.

**Comment by dimakuv** [comment]
There is clearly not enough enclave memory, based on your logs. E.g. you have lines like this:
```
[P1:T3:ServerZP] trace: ---- shim_mmap(0, 0x8000000, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0x0) ...
[P1:T3:ServerZP] trace: ---- return from shim_mmap(...) = -12
```

I don't see that you increased the size of the enclave? I still see this line in the log:
```
debug: Enclave created:
debug:     base:           0x0000000000000000
debug:     size:           0x0000000010000000   # this is 256MB
```

Did you forget to rebuild your stuff after you modified the `manifest.template` file?

**Comment by riturajsingh487** [comment]
I have not uploaded the updated logs in my previous post, my bad . 
I am uploading it now. 

> debug: Enclave created:
> debug:     base:           0x0000000000000000
> debug:     size:            0x0000000080000000

[gramine_server_epoll_zeromq_logs_updated.txt](https://github.com/gramineproject/gramine/files/9352765/gramine_server_epoll_zeromq_logs_updated.txt)

**Comment by dimakuv** [comment]
Thanks. I don't see anything special in the new log...

Could you try the latest `master` branch of Gramine? Maybe the bug was fixed in Gramine in the last couple months (since the release of Gramine v1.2).

**Comment by riturajsingh487** [comment]
Thanks for your reply.

I have tried with latest master branch of Gramine. But I am still getting the same issue.
Your help on this is greatly appreciated.

**Comment by dimakuv** [comment]
@riturajsingh487 Could you attach the new logs?

**Comment by riturajsingh487** [comment]
Hi, Below are the new logs.

[gramine_server_epoll_logs.txt](https://github.com/gramineproject/gramine/files/9405050/gramine_server_epoll_logs.txt)

Thanks again

**Comment by boryspoplawski** [comment]
This looks like a problem with our application, not Gramine.

**Comment by kailun-qin** [comment]
Hi @riturajsingh487,

Would just like to follow up - has your issue been resolved now? Thanks!

**Comment by dimakuv** [comment]
Let me close this issue, since it's been inactive for half a year.

@riturajsingh487 If the issue still persists, please give us more (and new) details, so that we can help identify the root cause. Also, please try the latest Gramine version.

**Comment by mkow** [comment]
> since it's been inactive for half a year

I'm against closing issues just because they's no activity in them for some time, it doesn't mean that the bug went away. Here we're closing it because the issue is likely in the original reporter's setup and they stopped replying to our questions.
